### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by jenstroeger** [chenjj/CORScanner#19]
Thanks for the useful package! One thing though:

    > pip install cors

I think is somewhat misleading and probably confusing for package maintainers who include this package, because I’m not including [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) but a CORS _scanner_. So, could you please rename the package

https://github.com/chenjj/CORScanner/blob/332ca147a1b311504758946f35bb314d2411fbd8/setup.py#L6

from `cors` to `corscanner` such that:

    > pip install corscanner

**Comment by chenjj** [comment]
Thanks, you can use `pip install corscanner` now.
