### ISSUE TITLE
Error in windows

### ISSUE THREAD

**Issue by razapoonja** [chenjj/CORScanner#2]
Traceback (most recent call last):
  File "cors_scan.py", line 6, in <module>
    from common.logger import Log
  File "C:\\..\\..\\CORScanner-master\common\logger.py", line 1, in <module>
    import fcntl
ImportError: No module named fcntl

**Comment by chenjj** [comment]
Thanks, @razapoonja. It seems that fcntl module isn't supported on Windows.  

I moved the "import fcntl" backwards. It's a temporary workaround if you don't need to use the "-o" option.

**Comment by razapoonja** [comment]
Thanks @chenjj for the quick temporary fix
