### ISSUE TITLE
Questions about redirection method

### ISSUE THREAD

**Issue by forkingna** [chenjj/CORScanner#22]
In the `common/corscheck.py` file, when the request is sent in the `send_req` method, the allow_redirects parameter is set to `True`. What are the considerations for this design? When detecting domain name A, if there is a redirection, I think the response from the first request should be used to determine whether the vulnerability exists, because after redirecting to domain B, the `access-control-allow-origin` parameter is set by domain B, it can no longer reflect the CORS status of the domain A.

**Comment by chenjj** [comment]
Thank for the question. I think we have considered the false positives caused by cross-domain redirections and have removed those cases using the following code:

https://github.com/chenjj/CORScanner/blob/dea5ed2f8fa8d424c3a874c2d66dddb4a58b7c9b/common/corscheck.py#L50-L55
