### ISSUE TITLE
增加任意域可信检测

### ISSUE THREAD

**Issue by Baikeryoyo** [chenjj/CORScanner#25]
https://github.com/saucer-man/CORScanner
https://github.com/saucer-man/CORScanner/commit/3af8499c8860e203f1d3264f287c19d047fafd93
在网上看到了这个，有网友发现没有检测access-control-allow-origin为*的安全问题

**Comment by chenjj** [comment]
谢谢你的建议和 PR。但是 access-control-allow-origin: * 好像不能被利用，不能造成安全问题。因为所有浏览器都不接受 access-control-allow-origin: * 和 access-control-allow-credentials： true 的组合。

我之前的[博客](https://www.jianjunchen.com/post/cors%E5%AE%89%E5%85%A8%E9%83%A8%E7%BD%B2%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/#2-6-origin-%E4%B8%8E-credentials-true-%E5%85%B1%E7%94%A8)里有提到这个。不知道现在有没有出新的利用方法。

**Comment by Baikeryoyo** [comment]
所以这个只算配置错误，不属于漏洞

**Comment by chenjj** [comment]
嗯，目前其它几类都直接安全危害。如果把这个加进去，可能会让人有些困惑，所以暂时先不加这个，不过还是谢谢你的建议。
