### ISSUE TITLE
通过代理扫描目标ip

### ISSUE THREAD

**Issue by NIAN-EVEN** [chenjj/CORScanner#26]
目标IP不直接可达时，需要走代理，希望增加指定代理服务器功能

**Comment by chenjj** [comment]
谢谢你的建议，刚加了 -p 选项。 更新后，可以使用。

pip install -r requirements.txt 
python cors_scan.py -u example.com -p http://127.0.0.1:8080

或者

pip install cors==1.0.0
cors -vu google.com -p socks5://127.0.0.1:8080
