### ISSUE TITLE
random characters like [91m is appearing in commond prompt

### ISSUE THREAD

**Issue by razapoonja** [chenjj/CORScanner#3]
![cors](https://user-images.githubusercontent.com/31192540/53303832-ecc09180-3890-11e9-894a-2bac3eac1df5.PNG)

I think colored font is not supported that's causing this.

**Comment by chenjj** [comment]
Thanks. According to https://pypi.org/project/colorama/, colorama module may be helpful. You could add the following code at the beginning of cors_scan.py.
```
from colorama import init
init()
```
But I don't have Windows for testing now. Are you interested in testing this and making a pull request?

**Comment by razapoonja** [comment]
Yes

**Comment by razapoonja** [comment]
Sure !
