### ISSUE TITLE
[ENHANCEMENT] Add developer third parties origin to check as bypasses

### ISSUE THREAD

**Issue by phackt** [chenjj/CORScanner#6]
Hello,

First of all thanks for this tool. Dealing with bypasses i also used to test some developer third parties websites like jsfiddle, codepen, github, gitlab, etc.... as origin.

What do you think to add this functionality to your tool ?

Regards,

**Comment by phackt** [comment]
i m currently developing the ability to provide a list of origins within a json file with, by default, dev third parties origins + a bit of refactoring.

**Comment by chenjj** [comment]
@phackt, nice suggestion, and thanks! It would be great if you can help with this and make a pull request.

**Comment by phackt** [comment]
@chenjj no prob, i also made a quick refactoring. I would like to review the output format also if it's ok for you just to output pure json with misconfigurations found.

**Comment by chenjj** [comment]
That makes sense. No problem for me.
