### ISSUE TITLE
[enchancement] response status code in results

### ISSUE THREAD

**Issue by phackt** [chenjj/CORScanner#9]
Hi Jianjun,

Hope you're well. Using CORScanner on a big scope i realized that i have a lot of false positive on 404 pages returning a permissive CORS. What do you think to add the last response status code in the json result in order to let people filter on code 200 for example?

Have a nice day.

**Comment by chenjj** [comment]
Good idea! Are you interested in making a pull request?

**Comment by phackt** [comment]
Yep i will work on it.

**Comment by phackt** [comment]
Close this one because merged
